"""remove join_code from household

Revision ID: 294cbce11375
Revises: 68485c00aae5
Create Date: 2026-05-11 17:53:41.725018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294cbce11375'
down_revision = '68485c00aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_column('join_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
