"""add current_household to user

Revision ID: 4a89134da175
Revises: 68c0a96da73e
Create Date: 2026-05-15 13:03:02.676488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a89134da175'
down_revision = '68c0a96da73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE user
        SET current_household = (
            SELECT household_id
            FROM membership
            WHERE membership.user_id = user.id
            LIMIT 1
        )
        WHERE current_household IS NULL
        """
    )
    op.execute(
        """
        UPDATE user
        SET current_household = (
            SELECT id FROM household LIMIT 1
        )
        WHERE current_household IS NULL
        """
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_household',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_household',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
