"""add last overdue popup to membership

Revision ID: 5acae5b26f47
Revises: 294cbce11375
Create Date: 2026-05-11 18:14:19.383608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acae5b26f47'
down_revision = '294cbce11375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_overdue_popup', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('last_overdue_popup')

    # ### end Alembic commands ###
