"""user current_household

Revision ID: 68c0a96da73e
Revises: 5acae5b26f47
Create Date: 2026-05-14 10:01:14.921027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c0a96da73e'
down_revision = '5acae5b26f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_household', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_current_household', 'household', ['current_household'], ['id'])

    # ### end Alembic commands ###

    # set default to first household they are a member of
    op.execute(
        """
        UPDATE user
        SET current_household = (
            SELECT household_id
            FROM membership
            WHERE membership.user_id = user.id
            LIMIT 1
        )
        WHERE current_household IS NULL
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_current_household', type_='foreignkey')
        batch_op.drop_column('current_household')

    # ### end Alembic commands ###
