"""user current_household

Revision ID: 68c0a96da73e
Revises: 5acae5b26f47
Create Date: 2026-05-14 10:01:14.921027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c0a96da73e'
down_revision = '5acae5b26f47'
branch_labels = None
depends_on = None


def upgrade():
    # Drop '_alembic_tmp_message' table if it exists
    conn = op.get_bind()
    inspector = sa.Inspector.from_engine(conn)  # type: ignore
    existing_tables = inspector.get_table_names()

    if "_alembic_tmp_user" in existing_tables:
        op.drop_table("_alembic_tmp_user")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_household', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_current_household', 'household', ['current_household'], ['id'])

    # ### end Alembic commands ###
    # since not nullable, we need to set a default value for existing records
    # set default to first household they are a member of
    op.execute(
        """
        UPDATE user
        SET current_household = (
            SELECT household_id
            FROM membership
            WHERE membership.user_id = user.id
            LIMIT 1
        )
        WHERE current_household IS NULL
        """
    )

    # now set the column to not nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_household', nullable=False)
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_current_household', type_='foreignkey')
        batch_op.drop_column('current_household')

    # ### end Alembic commands ###
