"""add completed_at to task

Revision ID: 90493e512b65
Revises: 3b6f19fddfbe
Create Date: 2026-05-11 10:35:08.131168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90493e512b65'
down_revision = '3b6f19fddfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
