"""empty message

Revision ID: c4d8a9b6ff14
Revises: 90493e512b65
Create Date: 2026-05-11 17:15:15.262149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d8a9b6ff14'
down_revision = '90493e512b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_column('streak')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
